<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/12/8
 * Time: 22:24
 */

namespace app\modules\admin\controllers;


use app\controllers\ConfigTrait;
use app\modules\admin\models\ConfigModel;
use yii\helpers\Url;
use yii\web\Controller;

class BaseController extends Controller
{

    public $isCheck = true;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        \Yii::$app->language = 'zh-CN';
        $this->layout = 'admin_layout';

        if($this->isCheck)
            $this->checkLogin();

        if(!ConfigTrait::isIniTed()) {

            $configModel = ConfigModel::findOne(1);
            if($configModel)
                ConfigTrait::configInit($configModel);
        }
    }


    public function renderJson($status=null, $message=null, $data=array(), $url = null, $break=false)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ((!is_null($status) && $message) || (is_array($data) && count($data) )) {
            \Yii::$app->response->data = [
                'status' => $status,
                'message' => $message,
                'data' => $data,
                'url' => $url
            ];
        } else {
            \Yii::$app->response->data = $status;
        }

        if($break){

            echo json_encode(\Yii::$app->response->data, JSON_UNESCAPED_UNICODE);
            exit;
        }

    }

    public function checkLogin($isJson=false){

        if(\Yii::$app->admin_user->isGuest && $isJson) {
            return $this->renderJson(STATUS_NOT_LOGIN, "您尚未登录,请先登录", [], null, true);
        } else if(\Yii::$app->admin_user->isGuest) {
            $this->redirect(Url::to(['/admin/public/login']));
        }
    }


}