<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/12/9
 * Time: 8:20
 */

namespace app\modules\admin\controllers;


use app\modules\admin\models\AdminModel;
use app\modules\admin\models\AdminUser;
use yii\captcha\CaptchaAction;
use yii\helpers\Url;

class PublicController extends BaseController
{
    public function init()
    {
        $this->isCheck = false;
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actions()
    {
        return [

            'captcha' => [
                'class' => CaptchaAction::className(),
                'minLength' => 7,
                'maxLength' => 7
            ]
        ];
    }

    public function register(){

    }

    public function actionLogin(){


        $adminModel = new AdminModel();
        if (\Yii::$app->request->isPost) {
            $rs = $adminModel->login(\Yii::$app->request->post());
            if ($rs){
                \Yii::$app->admin_user->login(AdminUser::findOne(['mobile'=>$adminModel->mobile]));
                return $this->redirect(Url::to(['/admin/index/index']));
            }
        }
        return $this->renderPartial('login', [
           'model' => $adminModel
        ]);
    }

    public function actionLogout(){
        \Yii::$app->admin_user->logout();
        return $this->redirect(Url::to(['/admin/public/login']));
    }

}