<?php
/**
 * Created by PhpStorm.
 * User: admin_
 * Date: 2017/9/23
 * Time: 19:13
 */

namespace app\common\components\widget;


use app\service\BtnService;
use yii\base\Widget;
use yii\helpers\Url;

class BtnWidget extends Widget
{

    public $btn_id;
    protected $model;

    public function __construct(array $config = [])
    {
        parent::__construct($config);

        $this->model = BtnService::getItem($this->btn_id);
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $url = "";
        switch ($this->model->id) {
            case 1:
                $url = Url::to(['site/page2']);
                break;

            case 2:
                $url = Url::to(['site/page2']);
                break;
            case 3:
                $url = Url::to(['site/page3']);
                break;

            case 4:
                $url = Url::to(['site/page3']);
                break;
            case 5:
                $url = Url::to(['site/page4']);
                break;

            default:
                break;
        }

        $template = <<<STD
            <span class="btn-tracking" data-id="{$this->model->id}" data-url="{$url}">{$this->model->display_text}</span>
STD;

        return $template;
    }



}