<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/12/9
 * Time: 16:40
 */

namespace app\modules\admin\models;


use yii\base\Behavior;
use yii\behaviors\TimestampBehavior;

class ArticleModel extends BaseModel
{

    public $imageFile;

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(),
            [
                'title' => '标题',
                'link' => '跳转url',
                'pic' => '图片',
                'imageFile' => '图片',
                'created_at' => '添加时间',
                'updated_at' => '更新时间',
            ]); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxSize' => '500000'],
            [
                ['title','link'],
                'required',
            ],
            [
                'title', function($attribute, $params){
                    if(!$this->pic && !$this->imageFile) {
                        $this->addError('imageFile', '图片不能为空');
                    }
                }
            ]
        ];
    }


    public function behaviors()
    {
        return [

            [
                'class' => TimestampBehavior::className()
            ]
        ];
    }

    public function scenarios()
    {
        return  array_merge(parent::scenarios(), [
            self::SCENARIO_DEFAULT => [
                'title',
                'link',
                'pic',
                'imageFile'
            ]
        ]);
    }


    public static function tableName()
    {
        return parent::getDbPrefix() . 'article';
    }

    public function beforeSave($insert)
    {
        $this->upload();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }



    public function upload()
    {
        if ($this->validate()) {
            $file = $this->imageFile;
            if($file) {
                $userId = \Yii::$app->admin_user->id;
                $picName = $userId . date('YmdHis') . '.' . $file->extension;
                $this->pic = $picName;
                $rs = $file->saveAs('uploads/article_pic/' . $picName);
                if( !$rs ){
                    $this->addError('imageFile', '上传失败!');
                }
                return $rs;
            } else {
                return true;
            }
        } else {
            return false;
        }
    }

    public function getFlushList(){
        return self::find()->where(['>', 'id',0])->all();
    }

    public function getPicRelUrl(){
        return '/uploads/article_pic/' . $this->pic;
    }
}