<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/11/25
 * Time: 23:25
 */

namespace app\controllers;


use app\modules\admin\models\ConfigModel;
use yii\base\Event;
use yii\helpers\Url;
use yii\web\Controller;
use yii\helpers\Json;
use yii\web\Response;
use app\controllers\ConfigTrait;

class BaseController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->language = 'zh-CN';
        if(!ConfigTrait::isIniTed()) {

            $configModel = ConfigModel::findOne(1);
            if($configModel)
                ConfigTrait::configInit($configModel);
        }
    }


    public function renderJson($status=null, $message=null, $data=array(), $url = null, $break=false)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        if ((!is_null($status) && $message) || (is_array($data) && count($data) )) {
            \Yii::$app->response->data = [
                'status' => $status,
                'message' => $message,
                'data' => $data,
                'url' => $url
            ];
        } else {
            \Yii::$app->response->data = $status;
        }

        if($break){

            echo json_encode(\Yii::$app->response->data, JSON_UNESCAPED_UNICODE);
            exit;
        }

    }

    public function checkLogin($isJson=false){
        if(\Yii::$app->user->isGuest && $isJson) {
            return $this->renderJson(STATUS_NOT_LOGIN, "您尚未登录,请先登录", [], null, true);
        } else if(\Yii::$app->user->isGuest) {
            $this->redirect(Url::to(['/site/login']));
        }
    }


    public static function check_wap(){
        // 先检查是否为wap代理，准确度高
        if(stristr($_SERVER['HTTP_VIA'],"wap")){
            return true;
        }
        // 检查浏览器是否接受 WML.
        elseif(strpos(strtoupper($_SERVER['HTTP_ACCEPT']),"VND.WAP.WML") > 0){
            return true;
        }
        //检查USER_AGENT
        elseif(preg_match('/(blackberry|configuration\/cldc|hp |hp-|htc |htc_|htc-|iemobile|kindle|midp|mmp|motorola|mobile|nokia|opera mini|opera |Googlebot-Mobile|YahooSeeker\/M1A1-R2D2|android|iphone|ipod|mobi|palm|palmos|pocket|portalmmm|ppc;|smartphone|sonyericsson|sqh|spv|symbian|treo|up.browser|up.link|vodafone|windows ce|xda |xda_)/i', $_SERVER['HTTP_USER_AGENT'])){
            return true;
        }
        else{
            return false;
        }
    }

}