<?php

namespace app\controllers;

use app\common\components\helpers\MapHelper;
use app\common\components\helpers\ToolsHelper;
use app\common\components\helpers\WeChatHelper;
use app\models\RegisterModel;
use app\models\RegisterUserInfoModel;
use app\models\TeamModel;
use app\models\TeamUserModel;
use app\models\UserIdentity;
use app\models\UserModel;
use app\models\UserMongoModel;
use app\models\WeChatModel;
use app\service\BtnClickTrackingService;
use app\service\GuestBookService;
use app\service\PageService;
use app\service\PageShowTrackingService;
use linslin\yii2\curl\Curl;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\Cookie;

class SiteController extends BaseController
{

    protected $theme = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(static::check_wap()) {
            $this->theme = "wap/";
            $this->layout = "wap_main.php";
        }
    }


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        $this->trackingPage(1);
        return $this->render($this->theme . 'index', [
            'model' => $this->getPageModel(1)
        ]);
    }public function actionPage2()
    {

        $this->trackingPage(2);
        return $this->render($this->theme . 'page2', [
            'model' => $this->getPageModel(2)
        ]);
    }public function actionPage3()
    {

        $this->trackingPage(3);
        return $this->render($this->theme . 'page3', [
            'model' => $this->getPageModel(3)
        ]);
    }public function actionPage4()
    {

        $this->trackingPage(4);
        return $this->render($this->theme . 'page4', [
            'model' => $this->getPageModel(4)
        ]);
    }

    public function actionGuestbook(){

        $data = Yii::$app->request->get();
        $service = new GuestBookService();
        $r = $service->create($data);
        return $this->renderJson($r ? 1 : 0, $r? '留言成功,非常感谢您的宝贵意见!' : '留言失败');

    }

    public function actionClickTracking(){

        $data = Yii::$app->request->get();
        $service = new BtnClickTrackingService();
        $data['ip'] = $_SERVER['REMOTE_ADDR'];
        $r = $service->create($data);
        return $this->renderJson($r ? 1 : 0, $r? '成功!' : '失败');

    }



    protected function getPageModel($id) {

        $pageService = new PageService();
        $model = $pageService->model->findOne($id);

        return is_null($model) ? [] : $model;
    }

    protected function trackingPage($id) {
        $pageTrackingService = new PageShowTrackingService();
        $pageTrackingService->create([
            'page_id' => $id,
            'ip' => $_SERVER['REMOTE_ADDR']
        ]);
    }

}
