<?php
/**
 * Created by PhpStorm.
 * User: xiaohongyang
 * Date: 2016/12/8
 * Time: 22:17
 */

namespace app\modules\admin;

use \yii\base\Module;
class AdminModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}